export enum FileContext {
    FORM_SUBMISSION = 'FORM_SUBMISSION',
    FORM_CERTIFICATE = 'FORM_CERTIFICATE',
    CERTIFICATE = 'CERTIFICATE',
    EVENT_ASSET = "EVENT_ASSET",
    USER_AVATAR = "USER_AVATAR",

}